

#Agent:
#  Driver: "ollama"
#  Api: "http://127.0.0.1:11434"
#  Model: "deepseek-r1:7b"
#  Temperature: 0.5

Agent:
  Driver: "openai"
  Url: "https://ark.cn-beijing.volces.com/api/v3"
  ApiKey: "27fbb257-c8e7-452b-810d-2ee0baccf4fc"
  Model: "deepseek-r1-250120"
  Temperature: 0.8

AgentTask:
  - Identity: "task1"
    Cron:
      AtTime:
        - "17:11:30"
    #      Duration: 1m
    LogID: "1"
    AlertID: "3"
    KBase:
      - "chroma"
    LogFilter:
      StartTime: "2025-03-05"
      InspName:
        - "1"

KBase:
  - Identity: "chroma"
    Driver: "chroma"
    Path: "http://localhost:8000"
    Collection: "ollama_embedding"
    Embedding:
      Driver: "ollama"
      BaseUrl: "http://127.0.0.1:11434"
      Model: "deepseek-r1:7b"
