

#Ai:
#  Driver: "ollama"
#  Api: "http://127.0.0.1:11434"
#  Model: "deepseek-r1:7b"
#  Temperature: 0.5

Agent:
  Driver: "openai"
  Url: "https://ark.cn-beijing.volces.com/api/v3"
  ApiKey: "27fbb257-c8e7-452b-810d-2ee0baccf4fc"
  Model: "deepseek-r1-250120"
  Temperature: 0.5

AiTask:
  - AiTaskName: "task1"
    Cron:
      AtTime:
        - "12:07:30"
    #      Duration: 1m
    LogID: 1
    AlertID: 3
    LogFilter:
      StartTime: 2025-03-4
      InspName:
        - "1"
