Default:
  DefaultDriver: "mysql"
  DefaultLogLevel: 2
  DefaultAlertLevel: 3

DB:
  - Name: "example1"
    Driver: "mysql"
    DSN: "root:03719@tcp(127.0.0.1:3306)/example1"
  - Name: "example2"
    Driver: "postgres"
    DSN: "host=127.0.0.1 port=5432 user=postgres dbname=postgres password=03719 sslmode=disable"

Table:
  - Name: "example_table1"
    DBConfig: "example_db1"
  - TableName: "example_table2"
    DBConfig: "example_db2"

Task:
  - Name: "task1"
    LogID: 1
    TargetDB:
      - "example1"
    Todo:
      - "1"
      - "2"
    Cron:
      Duration: 10m
#      AtTime:
#      - "13:00:01"

Log:
  - ID: 1
    Driver: "postgres"
    DBName: "example2"
    TableName: ""

Alert:
  - ID: 3
    Driver: "feishu"
    WebHook: "https://www.feishu.cn/flow/api/trigger-webhook/49e2149a6a2cbcfaa4baf7e46eadeae5"

Agent:
  Driver: "openai"
  Api: "https://ark.cn-beijing.volces.com/api/v3"
  ApiKey: "27fbb257-c8e7-452b-810d-2ee0baccf4fc"
  Model: "deepseek-r1-250120"
  Temperature: 0.5

AiTask:
  - Name: "task1"
    Cron:
      AtTime:
        - "12:07:30"
    #      Duration: 1m
    LogID: 1
    AlertID: 3
    LogFilter:
      StartTime: 2025-03-4
      InspName:
        - "1"
