Default:
  DefaultDriver: "mysql"
  DefaultLogLevel: "2"
  DefaultAlertLevel: "3"

DB:
  - Identity: "example1"
    Driver: "mysql"
    DSN: "root:03719@tcp(127.0.0.1:3306)/example1"
  - Identity: "example2"
    Driver: "postgres"
    DSN: "host=127.0.0.1 port=5432 user=postgres dbname=postgres password=03719 sslmode=disable"

Table:
  - Identity: "example_table1"
    DBConfig: "example_db1"
  - TableName: "example_table2"
    DBConfig: "example_db2"

Log:
  - Identity: "1"
    Driver: "postgres"
    DBName: "example2"
    TableName: ""

Alert:
  - Identity: "3"
    Driver: "feishu"
    WebHook: "https://www.feishu.cn/flow/api/trigger-webhook/49e2149a6a2cbcfaa4baf7e46eadeae5"
