Default:
  DefaultDriver: "mysql"
  DefaultLogLevel: 2
  DefaultAlertLevel: 3

DB:
  - Name: "example1"
    Driver: "mysql"
    DSN: "root:03719@tcp(127.0.0.1:3306)/example1"
  - Name: "example2"
    Driver: "postgres"
    DSN: "host=127.0.0.1 port=5432 user=postgres dbname=postgres password=03719 sslmode=disable"

Table:
  - TableName: "example_table1"
    DBConfig: "example_db1"
  - TableName: "example_table2"
    DBConfig: "example_db2"

Task:
  - Async: true
    TaskName: "task1"
    CheckCycle: 5m
    TargetDB:
      - "example1"
    Todo:
      - "1"
      - "2"
    Time:
      Duration: 10s
      AtTime:
      - "13:00:01"

Log:
  - ID: 0
    Driver: "postgres"
    DBName: "example2"
    TableName: ""

Alert:
  - AlertLevel: 3
  - AlertLevel: 4